const taglines = [
  "Positive Personality",
  "Multilingual",
  "Able to prioritize",
  "Good Communicator",
  "Honest",
  "Adaptable",
  "Planning Skills",
  "Resourceful",
  "Resourceful",
  "Excellent at time management and organization",
  "Great analytical skills",
  "Responsible",
  "Reliable",
  "Proactive",
  "Self-aware",
  "Open-minded",
  "Friendly",
  "Good listening skills",
  "Knowledgeable",
  "Dependable",
  "Empathetic",
  "Enthusiastic",
  "Able to focus on tasks at hand without distractions",
  "Artistic",
  "Detail-oriented",
  "Persistent",
  "Well-organized",
  "Problem-solver",
];
export default taglines;
